name: ethicompanion
description: Assistente ético para bem-estar digital e crescimento pessoal

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Material Design
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296

  # HTTP requests
  http: ^1.1.0
  dio: ^5.3.2

  # State management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Local storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  timeago: ^3.6.0

  # Networking and connectivity
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

  # UI enhancements
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.2
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0

  # Animations
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1

  # Theme and appearance
  dynamic_color: ^1.6.8
  flutter_colorpicker: ^1.0.3

  # Accessibility and internationalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and code quality
  flutter_lints: ^3.0.0
  
  # Testing
  mockito: ^5.4.2
  build_runner: ^2.4.7

  # Code generation
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600

# Flutter configuration
flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
